// 돈 패널의 소재와 동작. 오행은 장면 다양화 키이며 투자 성향·수익 예측을 뜻하지 않는다.
export const WEALTH = {
 wood: { ko: '{P}이 집의 재무 정리 테이블에서 저축 계획을 점검한다. 뚜껑 열린 동전 저금통, 동전 몇 묶음, 글자 없는 예산 분류 봉투와 무지 노트가 화면 중심이며 봉투에 동전을 나누어 놓는 손이 보인다', en: 'a young Korean {c} sorting savings at a home finance table, an open coin bank, a few grouped coins, blank budget envelopes and an unmarked notebook prominently visible, one hand calmly allocating coins between envelopes', motion: 'the character slowly places one coin beside a budget envelope, with a small natural hand movement', shot: '연출: 테이블 높이의 3/4 미디엄샷. 저금통·예산 봉투·동전을 나누는 손을 화면 상단과 중앙에 선명하게 배치한다' },
 fire: { ko: '{P}이 투자 검토 테이블에서 태블릿의 글자 없는 오르내리는 추상 차트와 서로 다른 크기의 자산 분류 토큰을 비교한다. 금융 차트와 토큰이 또렷하며 신중하게 검토하는 자세, 급등만 하는 차트는 피한다', en: 'a young Korean {c} carefully reviewing investment risk at a finance table, a tablet with a minimal unlabeled line rising and falling, several asset allocation tokens of different sizes, chart and tokens clearly visible, a thoughtful pose rather than excitement', motion: 'the character lightly points to one allocation token; the chart stays fixed and the tablet glow shifts softly', shot: '연출: 어깨 너머 오버숄더 미디엄샷. 화면 중앙의 태블릿 차트와 자산 토큰이 주인공이며 인물은 옆으로 물러난다' },
 earth: { ko: '{P}이 주거 자산과 장기 자금 계획을 점검한다. 집 모형, 열쇠, 적당량의 동전, 글자 없는 자금 분류 폴더가 한 테이블에 놓이며 집 모형 옆에 동전을 정리하는 손이 보인다', en: 'a young Korean {c} reviewing a housing asset and long-term savings plan at a table, a small model home, a key, a modest amount of coins and blank planning folders, a hand arranging coins beside the model home', motion: 'the character gently slides a planning folder beside the model home; curtains move very slightly', shot: '연출: 집 모형·열쇠·동전 위주의 비스듬한 하이앵글. 인물의 손과 상반신 일부가 테이블 가장자리에 보인다' },
 metal: { ko: '{P}이 자산을 분산하고 지출을 검토한다. 동전과 소박한 금속 자산 토큰을 서로 구분된 세 칸의 트레이에 정리하며 무지 카드와 글자 없는 정산 노트를 함께 놓는다. 분류하는 손과 트레이가 주인공', en: 'a young Korean {c} reviewing spending and diversifying savings, coins and modest metal asset tokens sorted into a three-compartment tray, a blank payment card and unmarked reconciliation notebook beside it, arranging hands and the tray as the focal point', motion: 'the character slowly shifts one token into a separate compartment, keeping all objects stable', shot: '연출: 자산 분류 트레이와 정산하는 손의 클로즈업. 얼굴은 프레임 가장자리에서 작게 보이거나 밖에 둔다' },
 water: { ko: '{P}이 비 내리는 창가에서 현금 흐름을 점검한다. 글자 없는 수입·지출 분류 봉투, 펼친 무지 가계부, 동전과 글자 없는 태블릿 막대 도형이 테이블 위에 있다. 서로 다른 높이의 막대와 봉투를 차분히 비교한다', en: 'a young Korean {c} reviewing cash flow at a table by a rainy window, separate blank income and expense envelopes, an open unmarked budget ledger, coins and a tablet with unlabeled bars of varying heights, calmly comparing the envelopes and chart', motion: 'the character gently moves an envelope beside the ledger while rain reflections shift on the window; chart shapes remain fixed', shot: '연출: 창가 테이블의 측면 미디엄샷. 가계부·분류 봉투·태블릿 도형이 인물보다 선명하게 보인다' }
};
export const WEALTH_GUARD_KO = '재테크·재물 관리 장면임이 한눈에 읽혀야 한다. 금융 소품과 이를 검토·분류하는 행동이 구도의 중심이다. 글자·숫자·통화 기호·브랜드 없이 동전, 무지 봉투, 차트 도형으로 표현한다. 인물이 없으면 금융 소품만 배치한다. 뛰기·점프·산책·장보기 구도로 바꾸지 않는다. 명품 쇼핑·돈다발 과시·대박 수익·수익 보장 연출은 피한다. 시대극이면 태블릿을 무지 장부와 자산 분류함으로 바꾸되 재물 관리 주제는 유지한다.';
export const WEALTH_GUARD_EN = 'Make personal finance and asset management unmistakable: financial props and a calm review or allocation gesture are the focal point. Use blank envelopes, coins and unlabeled chart shapes without letters, numbers, currency symbols or brands. If people are excluded, retain only the financial objects. No shopping, market stroll, running or jumping; no luxury display, piles of cash, jackpot or guaranteed profit imagery. For period settings, replace digital devices with an unmarked ledger and allocation boxes while keeping the finance theme.';
